name: ci

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        # os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.8.1

      - name: Run tests
        if: matrix.os == 'ubuntu-latest'
        run: yarn test

      - name: Run tests (without coverage)
        if: matrix.os != 'ubuntu-latest'
        run: yarn test-one "**/*_test.ts"

      - name: Generate codecov report
        if: matrix.os == 'ubuntu-latest'
        run: yarn coverage

      - name: Push codecov report
        if: matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash)
