name: ci

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.8.1

      - name: Run tests (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: deno test --unstable --import-map=import_map.json --coverage=./coverage/output **/*_test.ts

      - name: Run tests (win/mac)
        if: matrix.os != 'ubuntu-latest'
        run: deno test --unstable --import-map=import_map.json **/*_test.ts

      - name: Generate codecov report
        if: matrix.os == 'ubuntu-latest'
        run: deno coverage --unstable ./coverage --lcov > ./coverage/lcov.info

      - name: Push codecov report
        if: matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash)
